set exclu on
SET SAFETY OFF 

use afebacar
zap
use afectabco
zap
use cabcosto
zap
use cabefac
zap
use cabeprov
zap
use cabpresta
zap
use cabstock
zap
use cuecontra
zap
use cuecosto
zap
use cuepresta
zap
use cuerfac
zap
use cuerprov
zap
use cuestock
zap
use existencia
zap
use exctacte
zap
use movbacar
zap
use movbacte
zap
use movcaja
zap
use moviprov
zap
use movisto
zap
use movmerca
zap
use proveedor
repl all saldo with 0
use romaneo
zap
use tablaope
zap
use
SET SAFETY ON