#DEFINE DEBUGMODE_LIB_THREADS		.F.		&& MODO DE DEPURACIÓN PARA GENERAR LOG A MYTHREADFUNC.TXT


#DEFINE C_LONG_CODIGO			6		&& Longitud del código que indica la longitud del dato (estructura de la llamada)

*-- Prioridades de threads
#DEFINE THREAD_PRIORITY_LOWEST			-2
#DEFINE THREAD_PRIORITY_BELOW_NORMAL	-1
#DEFINE THREAD_PRIORITY_NORMAL			 0
#DEFINE THREAD_PRIORITY_ABOVE_NORMAL	 1
#DEFINE THREAD_PRIORITY_HIGHEST			 2

*-- Prioridades de proceso
#DEFINE PROCESS_QUERY_INFORMATION  1024
#DEFINE PROCESS_VM_READ            4
#DEFINE NORMAL_PRIORITY_CLASS      32
#DEFINE IDLE_PRIORITY_CLASS        64
#DEFINE HIGH_PRIORITY_CLASS        128
#DEFINE REALTIME_PRIORITY_CLASS    256
#DEFINE THREAD_BASE_PRIORITY_MAX   2

*-- File Mappings
#DEFINE PAGE_READWRITE			4
#DEFINE FILE_MAP_READ			4
#DEFINE FILE_MAP_WRITE			2
* FFFFFFFF (2^32) means: Use the Windows NT pagefile as the memory-mapped file.
* Otherwise, you could substitute a handle that you have created.
#DEFINE USEPAGEFILE				2^32
#DEFINE MAXBUFFERSIZE			254

#DEFINE WM_USER					0x400
#DEFINE CREATE_SUSPENDED		0x00000004
#DEFINE INFINITE				0xFFFFFFFF
#DEFINE WAIT_TIMEOUT			0x00000102
#DEFINE WAIT_OBJECT_0			0x00000000
#DEFINE ERROR_ALREADY_EXISTS	183
#DEFINE CLSCTX_INPROC_SERVER	1
#DEFINE CLSCTX_LOCAL_SERVER		4
#DEFINE VT_BSTR					8
