*-- KEYCODES.H

**************************************************************************
*
*   Valores para las teclas de Función (por el nombre)
*
**************************************************************************
#DEFINE NASCII_TECLA_PROCESAR		-1		&& F2
#DEFINE NASCII_TECLA_VALORES		-2		&& F3
#DEFINE NASCII_TECLA_GRABAR			-3		&& F4
#DEFINE NASCII_TECLA_IMPRIMIR		-4		&& F5
#DEFINE NASCII_TECLA_BUSCAR			-5		&& F6
#DEFINE NASCII_TECLA_CONSULTAR		-6		&& F7
#DEFINE NASCII_TECLA_ELIMINAR		-7		&& F8
#DEFINE NASCII_TECLA_SALIR			-8		&& F9
#DEFINE NASCII_TECLA_DEPURADOR		 134	&& F11



**************************************************************************
*
*   Valores ASCII para todas las teclas
*
**************************************************************************

*-- Teclas de Control

#DEFINE NKEYCODE_INS				22
#DEFINE NKEYCODE_SHIFT_INS			22
#DEFINE NKEYCODE_CTRL_INS			146
#DEFINE NKEYCODE_ALT_INS			162
#DEFINE NKEYCODE_INSERT				22
#DEFINE NKEYCODE_SHIFT_INSERT		22
#DEFINE NKEYCODE_CTRL_INSERT		146
#DEFINE NKEYCODE_ALT_INSERT			162

#DEFINE NKEYCODE_INICIO				1
#DEFINE NKEYCODE_SHIFT_INICIO		55
#DEFINE NKEYCODE_CTRL_INICIO		29
#DEFINE NKEYCODE_ALT_INICIO			151
#DEFINE NKEYCODE_HOME				1
#DEFINE NKEYCODE_SHIFT_HOME			55
#DEFINE NKEYCODE_CTRL_HOME			29
#DEFINE NKEYCODE_ALT_HOME			151

#DEFINE NKEYCODE_SUPR				7
#DEFINE NKEYCODE_SHIFT_SUPR			7
#DEFINE NKEYCODE_CTRL_SUPR			147
#DEFINE NKEYCODE_ALT_SUPR			163
#DEFINE NKEYCODE_DEL				7
#DEFINE NKEYCODE_SHIFT_DEL			7
#DEFINE NKEYCODE_CTRL_DEL			147
#DEFINE NKEYCODE_ALT_DEL			163

#DEFINE NKEYCODE_FIN				6
#DEFINE NKEYCODE_SHIFT_FIN			49
#DEFINE NKEYCODE_CTRL_FIN			23
#DEFINE NKEYCODE_ALT_FIN			159
#DEFINE NKEYCODE_END				6
#DEFINE NKEYCODE_SHIFT_END			49
#DEFINE NKEYCODE_CTRL_END			23
#DEFINE NKEYCODE_ALT_END			159

#DEFINE NKEYCODE_REPAG				18
#DEFINE NKEYCODE_SHIFT_REPAG		57
#DEFINE NKEYCODE_CTRL_REPAG			31
#DEFINE NKEYCODE_ALT_REPAG			153
#DEFINE NKEYCODE_PGUP				18
#DEFINE NKEYCODE_SHIFT_PGUP			57
#DEFINE NKEYCODE_CTRL_PGUP			31
#DEFINE NKEYCODE_ALT_PGUP			153

#DEFINE NKEYCODE_AVPAG				3
#DEFINE NKEYCODE_SHIFT_AVPAG		51
#DEFINE NKEYCODE_CTRL_AVPAG			30
#DEFINE NKEYCODE_ALT_AVPAG			161
#DEFINE NKEYCODE_PGDN				3
#DEFINE NKEYCODE_SHIFT_PGDN			51
#DEFINE NKEYCODE_CTRL_PGDN			30
#DEFINE NKEYCODE_ALT_PGDN			161

#DEFINE NKEYCODE_ARRIBA				5
#DEFINE NKEYCODE_SHIFT_ARRIBA		56
#DEFINE NKEYCODE_CTRL_ARRIBA		141
#DEFINE NKEYCODE_ALT_ARRIBA			152
#DEFINE NKEYCODE_UP					5
#DEFINE NKEYCODE_SHIFT_UP			56
#DEFINE NKEYCODE_CTRL_UP			141
#DEFINE NKEYCODE_ALT_UP				152

#DEFINE NKEYCODE_ABAJO				24
#DEFINE NKEYCODE_SHIFT_ABAJO		50
#DEFINE NKEYCODE_CTRL_ABAJO			145
#DEFINE NKEYCODE_ALT_ABAJO			160
#DEFINE NKEYCODE_DOWN				24
#DEFINE NKEYCODE_SHIFT_DOWN			50
#DEFINE NKEYCODE_CTRL_DOWN			145
#DEFINE NKEYCODE_ALT_DOWN			160

#DEFINE NKEYCODE_DERECHA				4
#DEFINE NKEYCODE_SHIFT_DERECHA			54
#DEFINE NKEYCODE_CTRL_DERECHA			2
#DEFINE NKEYCODE_ALT_DERECHA			157
#DEFINE NKEYCODE_RIGHT					4
#DEFINE NKEYCODE_SHIFT_RIGHT			54
#DEFINE NKEYCODE_CTRL_RIGHT				2
#DEFINE NKEYCODE_ALT_RIGHT				157

#DEFINE NKEYCODE_IZQUIERDA				19
#DEFINE NKEYCODE_SHIFT_IZQUIERDA		55
#DEFINE NKEYCODE_CTRL_IZQUIERDA			26
#DEFINE NKEYCODE_ALT_IZQUIERDA			155
#DEFINE NKEYCODE_LEFT					19
#DEFINE NKEYCODE_SHIFT_LEFT				55
#DEFINE NKEYCODE_CTRL_LEFT				26
#DEFINE NKEYCODE_ALT_LEFT				155

#DEFINE NKEYCODE_ESCAPE					27
#DEFINE NKEYCODE_SHIFT_ESCAPE			27
#DEFINE NKEYCODE_ESC					27
#DEFINE NKEYCODE_SHIFT_ESC				27

#DEFINE NKEYCODE_INTRO					13
#DEFINE NKEYCODE_SHIFT_INTRO			13
#DEFINE NKEYCODE_CTRL_INTRO				10
#DEFINE NKEYCODE_ENTER					13
#DEFINE NKEYCODE_SHIFT_ENTER			13
#DEFINE NKEYCODE_CTRL_ENTER				10

#DEFINE NKEYCODE_RETROCESO				127
#DEFINE NKEYCODE_SHIFT_RETROCESO		127
#DEFINE NKEYCODE_CTRL_RETROCESO			127
#DEFINE NKEYCODE_ALT_RETROCESO			14
#DEFINE NKEYCODE_BACKSPACE				127
#DEFINE NKEYCODE_SHIFT_BACKSPACE		127
#DEFINE NKEYCODE_CTRL_BACKSPACE			127
#DEFINE NKEYCODE_ALT_BACKSPACE			14

#DEFINE NKEYCODE_TAB					9
#DEFINE NKEYCODE_SHIFT_TAB				15
#DEFINE NKEYCODE_CTRL_TAB				148

#DEFINE NKEYCODE_ALT_BARRA				57
#DEFINE NKEYCODE_SPACEBAR				32
#DEFINE NKEYCODE_SHIFT_SPACEBAR			32
#DEFINE NKEYCODE_CTRL_SPACEBAR			32
#DEFINE NKEYCODE_ALT_SPACEBAR			57


*-- Teclas de Función

#DEFINE NKEYCODE_F1					28
#DEFINE NKEYCODE_SHIFT_F1			84
#DEFINE NKEYCODE_CTRL_F1			94
#DEFINE NKEYCODE_ALT_F1				104

#DEFINE NKEYCODE_F2					-1
#DEFINE NKEYCODE_SHIFT_F2			85
#DEFINE NKEYCODE_CTRL_F2			95
#DEFINE NKEYCODE_ALT_F2				105

#DEFINE NKEYCODE_F3					-2
#DEFINE NKEYCODE_SHIFT_F3			86
#DEFINE NKEYCODE_CTRL_F3			96
#DEFINE NKEYCODE_ALT_F3				106

#DEFINE NKEYCODE_F4					-3
#DEFINE NKEYCODE_SHIFT_F4			87
#DEFINE NKEYCODE_CTRL_F4			97
#DEFINE NKEYCODE_ALT_F4				107

#DEFINE NKEYCODE_F5					-4
#DEFINE NKEYCODE_SHIFT_F5			88
#DEFINE NKEYCODE_CTRL_F5			98
#DEFINE NKEYCODE_ALT_F5				108

#DEFINE NKEYCODE_F6					-5
#DEFINE NKEYCODE_SHIFT_F6			89
#DEFINE NKEYCODE_CTRL_F6			99
#DEFINE NKEYCODE_ALT_F6				109

#DEFINE NKEYCODE_F7					-6
#DEFINE NKEYCODE_SHIFT_F7			90
#DEFINE NKEYCODE_CTRL_F7			100
#DEFINE NKEYCODE_ALT_F7				110

#DEFINE NKEYCODE_F8					-7
#DEFINE NKEYCODE_SHIFT_F8			91
#DEFINE NKEYCODE_CTRL_F8			101
#DEFINE NKEYCODE_ALT_F8				111

#DEFINE NKEYCODE_F9					-8
#DEFINE NKEYCODE_SHIFT_F9			92
#DEFINE NKEYCODE_CTRL_F9			102
#DEFINE NKEYCODE_ALT_F9				112

#DEFINE NKEYCODE_F10				-9
#DEFINE NKEYCODE_SHIFT_F10			93
#DEFINE NKEYCODE_CTRL_F10			103
#DEFINE NKEYCODE_ALT_F10			113

#DEFINE NKEYCODE_F11				133
#DEFINE NKEYCODE_SHIFT_F11			135
#DEFINE NKEYCODE_CTRL_F11			137
#DEFINE NKEYCODE_ALT_F11			139

#DEFINE NKEYCODE_F12				134
#DEFINE NKEYCODE_SHIFT_F12			136
#DEFINE NKEYCODE_CTRL_F12			138
#DEFINE NKEYCODE_ALT_F12			140


*-- Números y Letras

#DEFINE NKEYCODE_1					49	
#DEFINE NKEYCODE_SHIFT_1			33	
#DEFINE NKEYCODE_CTRL_1				—	
#DEFINE NKEYCODE_ALT_1				120

#DEFINE NKEYCODE_2					50	
#DEFINE NKEYCODE_SHIFT_2			64	
#DEFINE NKEYCODE_CTRL_2				—	
#DEFINE NKEYCODE_ALT_2				121

#DEFINE NKEYCODE_3					51	
#DEFINE NKEYCODE_SHIFT_3			35	
#DEFINE NKEYCODE_CTRL_3				—	
#DEFINE NKEYCODE_ALT_3				122

#DEFINE NKEYCODE_4					52	
#DEFINE NKEYCODE_SHIFT_4			36	
#DEFINE NKEYCODE_CTRL_4				—	
#DEFINE NKEYCODE_ALT_4				123

#DEFINE NKEYCODE_5					53	
#DEFINE NKEYCODE_SHIFT_5			37	
#DEFINE NKEYCODE_CTRL_5				—	
#DEFINE NKEYCODE_ALT_5				124

#DEFINE NKEYCODE_6					54	
#DEFINE NKEYCODE_SHIFT_6			94	
#DEFINE NKEYCODE_CTRL_6				—	
#DEFINE NKEYCODE_ALT_6				125

#DEFINE NKEYCODE_7					55	
#DEFINE NKEYCODE_SHIFT_7			38	
#DEFINE NKEYCODE_CTRL_7				—	
#DEFINE NKEYCODE_ALT_7				126

#DEFINE NKEYCODE_8					56	
#DEFINE NKEYCODE_SHIFT_8			42	
#DEFINE NKEYCODE_CTRL_8				—	
#DEFINE NKEYCODE_ALT_8				127

#DEFINE NKEYCODE_9					57	
#DEFINE NKEYCODE_SHIFT_9			40	
#DEFINE NKEYCODE_CTRL_9				—	
#DEFINE NKEYCODE_ALT_9				128

#DEFINE NKEYCODE_0					48	
#DEFINE NKEYCODE_SHIFT_0			41	
#DEFINE NKEYCODE_CTRL_0				—	
#DEFINE NKEYCODE_ALT_0				19

#DEFINE NKEYCODE_a					97	
#DEFINE NKEYCODE_SHIFT_a			65	
#DEFINE NKEYCODE_CTRL_a				1	
#DEFINE NKEYCODE_ALT_a				30

#DEFINE NKEYCODE_b					98	
#DEFINE NKEYCODE_SHIFT_b			66	
#DEFINE NKEYCODE_CTRL_b				2	
#DEFINE NKEYCODE_ALT_b				48

#DEFINE NKEYCODE_c					99	
#DEFINE NKEYCODE_SHIFT_c			67	
#DEFINE NKEYCODE_CTRL_c				3	
#DEFINE NKEYCODE_ALT_c				46

#DEFINE NKEYCODE_d					100	
#DEFINE NKEYCODE_SHIFT_d			68	
#DEFINE NKEYCODE_CTRL_d				4	
#DEFINE NKEYCODE_ALT_d				32

#DEFINE NKEYCODE_e					101	
#DEFINE NKEYCODE_SHIFT_e			69	
#DEFINE NKEYCODE_CTRL_e				5	
#DEFINE NKEYCODE_ALT_e				18

#DEFINE NKEYCODE_f					102	
#DEFINE NKEYCODE_SHIFT_f			70	
#DEFINE NKEYCODE_CTRL_f				6	
#DEFINE NKEYCODE_ALT_f				33

#DEFINE NKEYCODE_g					103	
#DEFINE NKEYCODE_SHIFT_g			71	
#DEFINE NKEYCODE_CTRL_g				7	
#DEFINE NKEYCODE_ALT_g				34

#DEFINE NKEYCODE_h					104	
#DEFINE NKEYCODE_SHIFT_h			72	
#DEFINE NKEYCODE_CTRL_h				127	
#DEFINE NKEYCODE_ALT_h				35

#DEFINE NKEYCODE_I					105	
#DEFINE NKEYCODE_SHIFT_I			73	
#DEFINE NKEYCODE_CTRL_I				9	
#DEFINE NKEYCODE_ALT_I				23

#DEFINE NKEYCODE_j					106	
#DEFINE NKEYCODE_SHIFT_j			74	
#DEFINE NKEYCODE_CTRL_j				10	
#DEFINE NKEYCODE_ALT_j				36

#DEFINE NKEYCODE_k					107	
#DEFINE NKEYCODE_SHIFT_k			75	
#DEFINE NKEYCODE_CTRL_k				11	
#DEFINE NKEYCODE_ALT_k				37

#DEFINE NKEYCODE_l					108	
#DEFINE NKEYCODE_SHIFT_l			76	
#DEFINE NKEYCODE_CTRL_l				12	
#DEFINE NKEYCODE_ALT_l				38

#DEFINE NKEYCODE_n					110	
#DEFINE NKEYCODE_SHIFT_n			78	
#DEFINE NKEYCODE_CTRL_n				14	
#DEFINE NKEYCODE_ALT_n				49

#DEFINE NKEYCODE_o					111	
#DEFINE NKEYCODE_SHIFT_o			79	
#DEFINE NKEYCODE_CTRL_o				15	
#DEFINE NKEYCODE_ALT_o				24

#DEFINE NKEYCODE_q					113	
#DEFINE NKEYCODE_SHIFT_q			81	
#DEFINE NKEYCODE_CTRL_q				17	
#DEFINE NKEYCODE_ALT_q				16

#DEFINE NKEYCODE_r					114	
#DEFINE NKEYCODE_SHIFT_r			82	
#DEFINE NKEYCODE_CTRL_r				18	
#DEFINE NKEYCODE_ALT_r				19

#DEFINE NKEYCODE_s					115	
#DEFINE NKEYCODE_SHIFT_s			83	
#DEFINE NKEYCODE_CTRL_s				19	
#DEFINE NKEYCODE_ALT_s				31

#DEFINE NKEYCODE_t					116	
#DEFINE NKEYCODE_SHIFT_t			84	
#DEFINE NKEYCODE_CTRL_t				20	
#DEFINE NKEYCODE_ALT_t				20

#DEFINE NKEYCODE_u					117	
#DEFINE NKEYCODE_SHIFT_u			85	
#DEFINE NKEYCODE_CTRL_u				21	
#DEFINE NKEYCODE_ALT_u				22

#DEFINE NKEYCODE_v					118	
#DEFINE NKEYCODE_SHIFT_v			86	
#DEFINE NKEYCODE_CTRL_v				22	
#DEFINE NKEYCODE_ALT_v				47

#DEFINE NKEYCODE_w					119	
#DEFINE NKEYCODE_SHIFT_w			87	
#DEFINE NKEYCODE_CTRL_w				23	
#DEFINE NKEYCODE_ALT_w				17

#DEFINE NKEYCODE_x					120	
#DEFINE NKEYCODE_SHIFT_x			88	
#DEFINE NKEYCODE_CTRL_x				24	
#DEFINE NKEYCODE_ALT_x				45

#DEFINE NKEYCODE_y					121	
#DEFINE NKEYCODE_SHIFT_y			89	
#DEFINE NKEYCODE_CTRL_y				25	
#DEFINE NKEYCODE_ALT_y				21

#DEFINE NKEYCODE_z					122	
#DEFINE NKEYCODE_SHIFT_z			90	
#DEFINE NKEYCODE_CTRL_z				26	
#DEFINE NKEYCODE_ALT_z				44


*-- Símbolos

#DEFINE NKEYCODE_PUNTO				46		&&	.
#DEFINE NKEYCODE_2PUNTOS			58		&&	:
#DEFINE NKEYCODE_COMA				44		&&	,
#DEFINE NKEYCODE_PUNTOYCOMA			59		&&	;
#DEFINE NKEYCODE_ENEAVA				170		&&	ª
#DEFINE NKEYCODE_ENEAVO				186		&&	º
#DEFINE NKEYCODE_INICIOADMIRACION	161		&&	¡
#DEFINE NKEYCODE_FINADMIRACION		33		&&	!
#DEFINE NKEYCODE_DOBLECOMILLA		34		&&	"
#DEFINE NKEYCODE_COMILLADOBLE		34		&&	"
#DEFINE NKEYCODE_COMILLASIMPLE		39		&&	'
#DEFINE NKEYCODE_PUNTOMEDIO			183		&&	·
#DEFINE NKEYCODE_PESOS				36		&&	$
#DEFINE NKEYCODE_PORCIENTO			37		&&	%
#DEFINE NKEYCODE_AMPERSAND			38		&&	&
#DEFINE NKEYCODE_BARRA				47		&&	/
#DEFINE NKEYCODE_BARRAINVERTIDA		124		&&	\
#DEFINE NKEYCODE_INICIOPARENTESIS	40		&&	(
#DEFINE NKEYCODE_FINPARENTESIS		41		&&	)
#DEFINE NKEYCODE_IGUAL				61		&&	=
#DEFINE NKEYCODE_INICIOPREGUNTA		191		&&	¿
#DEFINE NKEYCODE_FINPREGUNTA		63		&&	?
#DEFINE NKEYCODE_ARROBA				64		&&	@
#DEFINE NKEYCODE_NUMERAL			35		&&	#
#DEFINE NKEYCODE_ALMOHADILLA		35		&&	#
#DEFINE NKEYCODE_ASTERISCO			42		&&	*
#DEFINE NKEYCODE_MENOS				45		&&	-
#DEFINE NKEYCODE_MAS				43		&&	+
#DEFINE NKEYCODE_EXPONENTE			94		&&	[
#DEFINE NKEYCODE_CORCHETEIZQDA		91		&&	]
#DEFINE NKEYCODE_CORCHETEDCHO		93		&&	{
#DEFINE NKEYCODE_LLAVEIZQDA			123		&&	#
#DEFINE NKEYCODE_LLAVEDCHA			125		&&	#

