*-- CONSTANTES PARA LOS CONTROLES ESTILO XP.
#INCLUDE "INCLUDE\CONTROLES_XP.H"

*-- CONSTANTES DE VISUAL FOXPRO
#INCLUDE "INCLUDE\FOXPRO.H"

*-- TECLAS
#INCLUDE "INCLUDE\KEYCODES.H"

*-- CONSTANTES DE LA API WIN32
#INCLUDE "INCLUDE\WIN32API.H"

*-- OTRAS CONSTANTES
#DEFINE CR		CHR(13)
#DEFINE LF		CHR(10)
#DEFINE CRLF	CHR(13) + CHR(10)
#DEFINE SPACE_10 	SPACE(10)
#DEFINE SPACE_20 	SPACE(20)
#DEFINE RAIZ_ABS	"RAIZ_ABS  "
