#DEFINE PR_DEFAULTLANGUAGE  "ENGLISH"

#DEFINE PR_IMGBTN_PREV		 "pr_previous.bmp"
#DEFINE PR_IMGBTN_NEXT		 "pr_next.bmp"
#DEFINE PR_IMGBTN_TOP		 "pr_top.bmp"
#DEFINE PR_IMGBTN_BOTT		 "pr_bottom.bmp"
#DEFINE PR_IMGBTN_MINI		 "pr_Locate.bmp" 
#DEFINE PR_IMGBTN_PRINT		 "pr_Print.bmp"
#DEFINE PR_IMGBTN_PRINTPREF	 "pr_PrintPref.bmp"
#DEFINE PR_IMGBTN_GOTOPG	 "pr_gotopage.bmp"
#DEFINE PR_IMGBTN_1PG		 "pr_1page.bmp"
#DEFINE PR_IMGBTN_2PG		 "pr_2page.bmp"
#DEFINE PR_IMGBTN_4PG		 "pr_4page.bmp"
#DEFINE PR_IMGBTN_CLOSE		 "pr_close.bmp" 
#DEFINE PR_IMGBTN_CLOSE2	 "pr_close2.bmp"
#DEFINE PR_IMGBTN_SAVE		 "pr_Save.bmp"
#DEFINE PR_IMGBTN_EMAIL		 "pr_Mail.bmp"
#DEFINE PR_IMGBTN_SETUP		 "pr_Gear.bmp"
#DEFINE PR_IMGBTN_SEARCH	 "pr_Search.bmp"
#DEFINE PR_IMGBTN_SEARCHAGAIN	 "pr_SearchAgain.bmp"
#DEFINE PR_IMGBTN_SEARCHBACK	 "pr_SearchBack.bmp"

#DEFINE PR_IMGBTN_PREV_32	 "pr_previous_32.bmp"
#DEFINE PR_IMGBTN_NEXT_32	 "pr_next_32.bmp"
#DEFINE PR_IMGBTN_TOP_32	 "pr_top_32.bmp"
#DEFINE PR_IMGBTN_BOTT_32	 "pr_bottom_32.bmp"
#DEFINE PR_IMGBTN_MINI_32	 "pr_Locate_32.bmp" 
#DEFINE PR_IMGBTN_PRINT_32	 "pr_Print_32.bmp"
#DEFINE PR_IMGBTN_PRINTPREF_32	 "pr_PrintPref_32.bmp"
#DEFINE PR_IMGBTN_GOTOPG_32	 "pr_gotopage_32.bmp"
#DEFINE PR_IMGBTN_1PG_32	 "pr_1page_32.bmp"
#DEFINE PR_IMGBTN_2PG_32	 "pr_2page_32.bmp"
#DEFINE PR_IMGBTN_4PG_32	 "pr_4page_32.bmp"
#DEFINE PR_IMGBTN_CLOSE_32	 "pr_close_32.bmp" 
#DEFINE PR_IMGBTN_CLOSE2_32	 "pr_close2_32.bmp"
#DEFINE PR_IMGBTN_SAVE_32	 "pr_Save_32.bmp"
#DEFINE PR_IMGBTN_EMAIL_32	 "pr_Mail_32.bmp"
#DEFINE PR_IMGBTN_SETUP_32	 "pr_Gear_32.bmp"
#DEFINE PR_IMGBTN_SEARCH_32	 "pr_Search_32.bmp"
#DEFINE PR_IMGBTN_SEARCHAGAIN_32 "pr_SearchAgain_32.bmp"
#DEFINE PR_IMGBTN_SEARCHBACK_32 "pr_SearchBack_32.bmp"


#DEFINE PR_FORMICON  "wwrite.ico"