PROCEDURE directivasvarias

PUBLIC FILE_NOTIFY_CHANGE_FILE_NAME,FILE_NOTIFY_CHANGE_DIR_NAME,FILE_NOTIFY_CHANGE_ATTRIBUTES,FILE_NOTIFY_CHANGE_SIZE
PUBLIC FILE_NOTIFY_CHANGE_LAST_WRITE,FILE_NOTIFY_CHANGE_LAST_ACCESS,FILE_NOTIFY_CHANGE_CREATION,FILE_NOTIFY_CHANGE_SECURITY
PUBLIC INVALID_HANDLE_VALUE,WAIT_OBJECT_0,WATCHING_INTERVAL


FILE_NOTIFY_CHANGE_FILE_NAME   = 1
FILE_NOTIFY_CHANGE_DIR_NAME    = 2
FILE_NOTIFY_CHANGE_ATTRIBUTES  = 4
FILE_NOTIFY_CHANGE_SIZE        = 8
FILE_NOTIFY_CHANGE_LAST_WRITE  = 16
FILE_NOTIFY_CHANGE_LAST_ACCESS = 32
FILE_NOTIFY_CHANGE_CREATION    = 64
FILE_NOTIFY_CHANGE_SECURITY    = 128
INVALID_HANDLE_VALUE           = -1
WAIT_OBJECT_0                  = 0
WATCHING_INTERVAL              = 1000  && milliseconds


*!*	PUBLIC WAIT_TIMEOUT,ERROR_ALREADY_EXISTS,WM_USER

*!*	WAIT_TIMEOUT          = 258
*!*	ERROR_ALREADY_EXISTS  = 183
*!*	WM_USER               = 0x400

ENDPROC

DEFINE CLASS Filestructure As Custom 
	nombre   = ""
	tamano   = 0
	fechamod = {}
	horamod  = ""
ENDDEFINE 


